### ISSUE TITLE
OHRI Technical Roadmap

### ISSUE THREAD

**Issue by kajambiya** [UCSF-IGHS/openmrs-esm-ohri#1661]
### Feature Work
- [ ] **Form Engine (Parity with Angular form engine)**
  - [x] Support rendering type "drug"
  - [x] Ability to mark a form field as transient.
  - [x] Support injecting of external data sources.
  - [x] Support registration of custom expressions.
  - [ ] Support for creation of reusable components.
  - [ ] Support for rendering problem by concept class.
  - [x] Support for file attachment rendering.
  - [ ] Concept location support.
  - [ ] Adjust the rest-web-services module to allow filtering of voided forms.
  - [ ] Form submission should use the `form_uuid `and `encounter_uuid `fetched from the backend.
  - [ ] Support for Z function as part of inbuilt Expression helpers.
  - [ ] Support translation/localisation (i18n) in labels.
  - [ ] Support for Drug Orders.
- [ ] **Form Builder**
  - [x] Display of Audit information on the form editor.
  - [ ] Support for referencing reusable components.
- [ ] **Mamba ETL**
  - [ ] Move MambaETL DB flattening Task scheduler to base module.
  - [ ] Support for flattening concepts rendered as both questions and answers.
  - [x] A configurable toggle between storing ETL output in the OpenMRS database or in External database.
  - [ ] Ensure that reports data is available while ETL is running.
  - [ ] Incremental update of ETL based on underlying data changes.
  - [ ] Automate addition of Make Scripts in MambaETL.
  - [ ] Service/API layer data pagination support in MambaETL.
  - [ ] Automate column naming in the ETL flattened Tables.
  - [ ] ObsGroups support for MambaETL.
  - [ ] Publish Version 2.0 of MambaETL.

### Bugs
- [ ] **Mamba ETL**
  - [ ] Fix build failure when reports.json configuration file is missing.
  - [x] Concepts with multi-select values (e.g. key population) failing to flatten.
- [ ] **Form Engine**
  - [x] Previous values are picked from old encounters. 
  

### House Keeping
- [ ] **Form Engine**
  - [ ] Update Form Engine Documentation.
  - [ ] Comparison of validation in RFE against AFE.
- [ ] **Mamba ETL**
  - [ ] Test report on MambaETL running on MySQL 8.
  - [ ] MambaETL documentation - v1.0.0.
  - [ ] Performance improvement during the flattening process.
  - [ ] Robust Error Handling in MambaETL.
  - [ ] Code cleanups and Refactors in MambaETL.

**Comment by kajambiya** [comment]
Moved to respective repositories
